### ISSUE TITLE
The logo screen is forever

### ISSUE THREAD

**Issue by tebrobert** [RoepStoep/lidrobile#1]
**I'm submitting a ...** :
- bug report

# Bug report

**Current behavior:**

When the app starts it shows the white screen with the Lidraughts logo. The logo screen is staying forever on my phone.

**Expected behavior:**

On other people's phones the logo screen is being displayed for about a second and then the game menu is displayed.

**Steps to reproduce:**

On my phone: just start the application, nothing more.

**Environment information**

- phone hardware: Meizu M5c, About phone section: Product name - M5c, Model - M710H, Serial number - 710HZCRD228PV)
- phone operating system version, About phone section: Android version - 6.0, Android security patch date - "March 5, 2017", Build number - Flyme 6.0.2.3G
- version of lidraughts mobile: latest, 1.2.0

**Other information:**

The is no updates for my phone's system.

The Android System WebView is updated, version 87.0.4280.101

**Comment by RoepStoep** [comment]
Please update to the latest version 2.1.0. It contains many bugfixes and is rewritten in a more modern framework, which is likely to solve problems you may have had with the previous versions.
